name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-22.04, ubuntu-24.04]

    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version-file: .nvmrc
    - run: npm run ci
    - run: npm run build
